import SwiftUI

struct ReadAloudGuideView: View {
    private enum Phase {
        case preparing
        case silent
        case ready
    }

    @Environment(MuseumTheme.self) private var theme

    @State private var speaker = ReadAloudSpeaker()
    @State private var spokenText: String?

    let html: String
    let languageCode: String

    private var phase: Phase {
        guard let spokenText else { return .preparing }
        if spokenText.isEmpty { return .silent }
        return speaker.phase == .preparing ? .preparing : .ready
    }

    var body: some View {
        HStack(spacing: 12) {
            switch phase {
            case .preparing:
                ProgressView().controlSize(.small)
                Text("Preparing the reading")
                    .font(.museumCaption)
                    .foregroundStyle(.secondary)

            case .silent:
                EmptyView()

            case .ready:
                Button {
                    speaker.togglePlayback(of: spokenText ?? "", spokenIn: languageCode)
                } label: {
                    Image(systemName: speaker.isSpeaking ? "pause.circle.fill" : "play.circle.fill")
                        .font(.museumAudioControl)
                        .foregroundStyle(theme.accent)
                }
                .buttonStyle(.plain)
                .accessibilityLabel(speaker.isSpeaking ? "Pause" : "Play")
                .padding(.trailing, 4)

                VStack(alignment: .leading, spacing: 4) {
                    Text("Read aloud")
                        .font(.museumBody)

                    Label("Autogenerated", systemImage: "wand.and.sparkles")
                        .font(.museumCaption)
                        .foregroundStyle(.secondary)
                }
            }

            Spacer(minLength: 0)
        }
        .task(id: html) {
            speaker.stop()
            spokenText = html.strippingHTMLTagsKeepingLineBreaks
        }
        .onDisappear { speaker.stop() }
    }
}
